<h2>Мои навыки</h2>                        
<p>Adobe Photoshop</p>
<div class="skill1"></div>
<div class="skill1_2"></div>
<p>Adobe Photoshop</p>
<div class="skill2"></div>
<div class="skill2_2"></div>
<p>Adobe Photoshop</p>
<div class="skill3"></div>
<div class="skill3_2"></div>